---
title: "Group 43 UCSB domestic grad enrollment"
author: "Thomas Lenihan and Jessica West"
date: "11/15/2021"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
```

```{r}
ucsb_grad <- read_csv(here ("data", "ucsb_grad_data.csv")) %>% 
                        mutate(Ethnicity = ethnicity)
```

```{r}
ggplot(data = ucsb_grad,
       aes(x = year_abbr,
           y = domestic_enrollment, 
           color = Ethnicity)) +
  geom_col(position = "fill") +
    labs(x = "Year",
      y = "Change in Domestic Graduate Enrollment",
      title = "Proportion of Graduate Student Enrollment by Ethnicity, 2008-2019",
      caption = "Source: UCSB Office of Budget and Planning")+
  theme(plot.title = element_text(size = 12, hjust = -0.5))+
  theme_minimal()
```

**Figure 1 - Ethnic Distributions of New Graduate Students, 2008-2019.** Data is from the UCSB Office of Budget and Planning Campus Profiles. Columns are proportions of total ethnic diversity, not absolute counts.